---
ansible_ssh_user: ubuntu
ansible_ssh_private_key_file: "~/.ssh/id_rsa"

required_packages:
  - nginx
  - git
  - curl

firewall_rules:
  - { rule: 'allow', port: 'ssh' }
  - { rule: 'allow', port: 'http' }
  - { rule: 'deny', port: '8080' }
  - { rule: 'deny', port: '21' }